services:
  planrr-frontend:
    container_name: planrr-frontend
    image: git.postfmly.com/admin/planrr-frontend:arm64
    restart: unless-stopped
    depends_on:
      - planrr-backend
    ports:
      - "91:80"
    environment:
      - TZ=America/Chicago
    labels:
      - wud.display.name=Planrr (Frontend)
      - homepage.group=Personal
      - homepage.name=Planrr
      - homepage.icon=https://plan.postfmly.com/planrr.png
      - homepage.href=https://plan.postfmly.com/
      - homepage.description=plan.postfmly.com

  planrr-backend:
    container_name: planrr-backend
    image: git.postfmly.com/admin/planrr-backend:arm64
    restart: unless-stopped
    ports:
      - "5557:5557"
    volumes:
      - db:/backend/db
    environment:
      - TZ=America/Chicago
    labels:
      - wud.display.name=Planrr (Backend)
    stop_signal: SIGINT

volumes:
  db:

networks: {}

x-dockge:
  urls:
    - https://plan.postfmly.com
