@host = http://localhost:{{$dotenv API_PORT}}/api

###

@rnd_id = {{$randomInt 10000 20000}}
@rnd_day = {{$randomInt 0 7}}

###

// Get API version

GET {{host}}/version

###

// Get all meals

GET {{host}}/get

###

// Get meal by ID
// NOTE: meal ID does not exist

GET {{host}}/get/{{rnd_id}}

###

// Get meal by ID

GET {{host}}/get/1

###

// Add meal

POST {{host}}/add
Content-Type: application/json

{
    "day": {{rnd_day}},
    "title": "TEST {{rnd_id}}",
    "description": "TEST ME {{rnd_id}}"
}

###

// Update meal by ID
// NOTE: meal ID does not exist

PUT {{host}}/update/{{rnd_id}}
Content-Type: application/json

{
    "day": {{rnd_day}},
    "title": "NOGO"
}

###

// Update meal by ID

PUT {{host}}/update/1
Content-Type: application/json

// NOTE: pass exisisting data elements
{
    "day": {{rnd_day}},
    "title": "MODIFIED {{rnd_id}}",
    "description": "MODIFIED {{rnd_id}}"
}

###

// Delete meal by ID
// Error: meal does not exist

DELETE {{host}}/delete/{{rnd_id}}

###

// Delete meal by ID

DELETE {{host}}/delete/1
